version: '3.3'

services:
  jenkins:
    container_name: jenkins
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home: